{
 "title": "Apollo GraphQL Metrics",
 "description": "Apollo GraphQL metrics. Mutations/errors/operations.",
 "tags": [
  "graphql",
  "prometheus",
  "nestjs"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(graphql_queries_responded, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queries",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(graphql_queries_resolved{instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum(increase(graphql_queries_errors{instance=\"$instance\"}[$__range]) OR vector(0)) / sum(increase(graphql_queries_resolved{instance=\"$instance\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(graphql_queries_errored{instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Query Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(graphql_queries_errored{instance=\"$instance\", operation=\"query\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Mutation Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(graphql_queries_errored{instance=\"$instance\", operation=\"mutation\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(operation, operationName) (increase(graphql_queries_errored{instance=\"$instance\"}[$__range])) > 0"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Queries",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(graphql_queries_resolved{instance=\"$instance\", operation=\"query\"}[$__range])) by (operationName) > 0"
    }
   ]
  },
  {
   "title": "Mutations",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(graphql_queries_resolved{instance=\"$instance\", operation=\"mutation\"}[$__range])) by (operationName) > 0"
    }
   ]
  },
  {
   "title": "Total numbers of Queries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(graphql_queries_resolved{instance=\"$instance\", operation=\"query\"}[$__rate_interval])",
     "legendFormat": "{{operationName}}"
    }
   ]
  },
  {
   "title": "Total numbers of Mutations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(graphql_queries_resolved{instance=\"$instance\", operation=\"mutation\"}[$__rate_interval])",
     "legendFormat": "{{operationName}}"
    }
   ]
  },
  { "title": "Field Resolvers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Total numbers of field resolver requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(graphql_resolver_time_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{parentType}}.{{fieldName}} - {{returnType}}"
    }
   ]
  },
  {
   "title": "Average inbound field resolver duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(graphql_resolver_time_sum{instance=\"$instance\"}[$__rate_interval]) / rate(graphql_resolver_time_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{parentType}}.{{fieldName}} - {{returnType}}"
    }
   ]
  }
 ]
}